### ISSUE TITLE
Require PAT in non-demo mode to verify identity

### ISSUE THREAD

**Issue by derekbekoe** [derekbekoe/convey#21]
Save token in config file with r/w only for user.
* Provide interactive way to pass in this PAT.
* Include instruction to create PAT from https://github.com/settings/tokens with user:email scope only.

- https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#non-web-application-flow
- https://developer.github.com/v3/auth/#via-oauth-tokens

**Comment by hlubovac** [comment]
Maybe somebody should close this due to inactivity - since that's what @derekbekoe likes doing to others.
